#!/bin/bash

if [ "${#1}" -lt 1 ]; then
    echo ""
    echo "USAGE"
    echo ""
    echo "install_dev <profile>"
    echo "  to install the site with the <profile> and enable dev modules and settings"
    echo ""
    echo "install_dev --skip-siteinstall"
    echo "install_dev -s"
    echo "  to only enable dev modules and settings on an existing install"
    echo ""
    echo "TIP"
    echo ""
    echo "To make it easy to use this script, create an alias in your .bashrc file:"
    echo "  alias drupal-install=\"\\\`drush dd\\\`/sites/all/modules/devmodules7/install_dev\""
    echo "This assumes that you have symlinked to devmodules at /sites/all/modules/devmodules7"
    echo ""
    exit 1;
fi

# install drupal with the install profile unless this should be skipped
if [ "$1" != "--skip-siteinstall" ] && [ "$1" != "-s" ]; then
    drush -y si $1
fi

# enable some development modules
drush -y en devel \
            diff \
            environment_indicator \
            coffee \
            field_ui \
            views_ui \
            dummyimage \
            ftools \
            module_filter

# disable some modules
drush -y dis update \
             overlay

# change the superuser to admin/admin
drush sqlq "update users set name='admin' where uid=1;"
drush upwd admin --password=admin

# launch a PHP script to further configure drupal
drush -y scr `dirname $0`/install_dev.php
